version: '2.2'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres:11
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello
      - POSTGRES_DB=hello_dev

  phpmyadmin:
    image: zhajor/docker-phppgadmin
    ports:
      - '81:80'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
